<?php

namespace AppBundle\Repository;

/**
 * TaxonomyTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomyTermRepository extends \Doctrine\ORM\EntityRepository
{
}
