<?php

namespace AppBundle\Repository;

/**
 * TaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomyRepository extends \Doctrine\ORM\EntityRepository
{
}
