<?php

namespace AppBundle\Repository;

/**
 * UserOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
