<?php

namespace AppBundle\Repository;

/**
 * SysConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
